### ISSUE TITLE
Cannot build in OpenSUSE 12.3, SCons don't find Speech Dispatcher

### ISSUE THREAD

**Issue by Oliverity** [Olga-Yakovleva/RHVoice#99]
Здравствуйте!

Пытаюсь собрать RHVoice на OpenSUSE 12.3. Похоже, SCons не обнаруживает Speech Dispatcher. Это немного странно, поскольку Speech Dispatcher в системе установлен. Пытался понять по коду, как именно SCons проверяет его наличие, но, увы, не смог разобраться. Не могли бы Вы подсказать, как именно такая проверка происходит? Ниже привожу сообщения SCons, а далее - ту информацию о Speech Dispatcher в системе, которая, надеюсь, может быть полезна:

```
~/RHVoice-master> scons -h
scons: Reading SConscript files ...
Mkdir("build/linux")
Checking whether the C compiler worksyes
Checking whether the C++ compiler worksyes
Checking for pkg-config... yes
Checking for libpulse-simple... yes
Checking for ao... yes
Checking for portaudio-2.0... yes
Checking Speech Dispatcher version ... no
AttributeError: 'SConsEnvironment' object has no attribute 'InstallVersionedLib':
  File "/home/oleg/Downloads/RHVoice-master/SConstruct", line 343:
    build_for_linux(base_env,vars)
  File "/home/oleg/Downloads/RHVoice-master/SConstruct", line 297:
    build_binaries(base_env,user_vars)
  File "/home/oleg/Downloads/RHVoice-master/SConstruct", line 294:
    duplicate=0)
  File "/usr/lib64/python2.7/site-packages/SCons/Script/SConscript.py", line 614:
    return method(*args, **kw)
  File "/usr/lib64/python2.7/site-packages/SCons/Script/SConscript.py", line 551:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/usr/lib64/python2.7/site-packages/SCons/Script/SConscript.py", line 260:
    exec _file_ in call_stack[-1].globals
  File "/home/oleg/Downloads/RHVoice-master/src/core/SConscript", line 72:
    local_env.InstallLibrary(lib)
  File "/usr/lib64/python2.7/site-packages/SCons/Environment.py", line 223:
    return self.method(*nargs, **kwargs)
  File "/home/oleg/Downloads/RHVoice-master/site_scons/site_tools/installer.py", line 67:
    return InstallSharedLibrary(env,src)
  File "/home/oleg/Downloads/RHVoice-master/site_scons/site_tools/installer.py", line 63:
    return Install(env,src,"$libdir",shlib=True,mode=0o755)
  File "/home/oleg/Downloads/RHVoice-master/site_scons/site_tools/installer.py", line 34:
    inst=env.InstallVersionedLib(destpath,src)
```

Что пока посмотрел сам. Таких переменных окружения, как `spd_version`, `LIBSPEECHD_MAJOR_VERSION` или `LIBSPEECHD_MINOR_VERSION`, в системе нет.

Установлены следующие пакеты:
```
speech-dispatcher-0.7.1-12.1.2.x86_64
speech-dispatcher-configure-0.7.1-12.1.2.x86_64
speech-dispatcher-module-espeak-0.7.1-12.1.2.x86_64
```

После обнаружения проблемы доустановил ещё debug-пакеты, но это ничего не изменило; devel-пакетов для Speech Dispatcher в репозитории нет.
```
speech-dispatcher-module-espeak-debuginfo-0.7.1-12.1.2.x86_64
speech-dispatcher-debuginfo-0.7.1-12.1.2.x86_64
speech-dispatcher-debugsource-0.7.1-12.1.2.x86_64
```

По файлам состав `speech-dispatcher-0.7.1-12.1.2.x86_64` таков (после обнаружения проблемы сделал симлинки `/usr/lib/speech-dispatcher` и `/usr/lib/speech-dispatcher-modules` на соответствующие папки в `/usr/lib64` - но тоже безрезультатно):
```
/etc/init.d/speech-dispatcher
/etc/logrotate.d/speech-dispatcher
/etc/speech-dispatcher
/etc/speech-dispatcher/clients
/etc/speech-dispatcher/clients/emacs.conf
/etc/speech-dispatcher/clients/gnome-speech.conf
/etc/speech-dispatcher/modules
/etc/speech-dispatcher/modules/cicero.conf
/etc/speech-dispatcher/modules/dtk-generic.conf
/etc/speech-dispatcher/modules/epos-generic.conf
/etc/speech-dispatcher/modules/espeak-generic.conf
/etc/speech-dispatcher/modules/espeak-mbrola-generic.conf
/etc/speech-dispatcher/modules/festival.conf
/etc/speech-dispatcher/modules/llia_phon-generic.conf
/etc/speech-dispatcher/modules/swift-generic.conf
/etc/speech-dispatcher/speechd.conf
/usr/bin/clibrary
/usr/bin/clibrary2
/usr/bin/connection_recovery
/usr/bin/spd-say
/usr/bin/spd_long_message
/usr/bin/spd_run_test
/usr/bin/spdsend
/usr/bin/speech-dispatcher
/usr/lib64/speech-dispatcher
/usr/lib64/speech-dispatcher-modules
/usr/lib64/speech-dispatcher-modules/sd_cicero
/usr/lib64/speech-dispatcher-modules/sd_dummy
/usr/lib64/speech-dispatcher-modules/sd_festival
/usr/lib64/speech-dispatcher-modules/sd_generic
/usr/lib64/speech-dispatcher/libsdaudio.so
/usr/lib64/speech-dispatcher/libsdaudio.so.2
/usr/lib64/speech-dispatcher/libsdaudio.so.2.0.4
/usr/sbin/rcspeech-dispatcher
/usr/share/doc/packages/speech-dispatcher
/usr/share/doc/packages/speech-dispatcher/AUTHORS
/usr/share/doc/packages/speech-dispatcher/COPYING
/usr/share/doc/packages/speech-dispatcher/ChangeLog
/usr/share/doc/packages/speech-dispatcher/NEWS
/usr/share/doc/packages/speech-dispatcher/README
/usr/share/info/spd-say.info.gz
/usr/share/info/speech-dispatcher.info.gz
/usr/share/info/ssip.info.gz
/usr/share/sounds/speech-dispatcher
/usr/share/sounds/speech-dispatcher/dummy-message.wav
/usr/share/sounds/speech-dispatcher/test.wav
/var/log/speech-dispatcher
```

У пакета `speech-dispatcher-configure-0.7.1-12.1.2.x86_64` такой состав:
```
/usr/bin/spd-conf
/usr/lib64/python2.7/site-packages/speechd_config
/usr/lib64/python2.7/site-packages/speechd_config/__init__.py
/usr/lib64/python2.7/site-packages/speechd_config/__init__.pyc
/usr/lib64/python2.7/site-packages/speechd_config/__init__.pyo
/usr/lib64/python2.7/site-packages/speechd_config/config.py
/usr/lib64/python2.7/site-packages/speechd_config/config.pyc
/usr/lib64/python2.7/site-packages/speechd_config/config.pyo
/usr/lib64/python2.7/site-packages/speechd_config/paths.py
/usr/lib64/python2.7/site-packages/speechd_config/paths.pyc
/usr/lib64/python2.7/site-packages/speechd_config/paths.pyo
```

**Comment by Olga-Yakovleva** [comment]
Проверка наличия Speech Dispatcher важна только для его последней версии 
- 0.9, где синтезатор должен в одном случае изменить поведение при 
взаимодействии с ним.

В данном случае исключение связано с SCons. Видимо, в той версии, 
которая у вас установлена, ещё не была реализована функциональность по 
установке динамических библиотек, которую я стала использовать некоторое 
время назад. Возможно, мне стоит распространять локальную копию SCons в 
своих исходниках, чтобы не думать о разных версиях.

Вы пока можете попробовать собрать с помощью той же самой так называемой 
локальной версии, которая не требует установки:
http://prdownloads.sourceforge.net/scons/scons-local-3.0.1.tar.gz

**Comment by Oliverity** [comment]
Спасибо! Задал переменную spd_version вручную в параметрах запуска Вашего SCons, доустановил девелоперские либы ALSA, и всё скомпилировалось и установилось.
